// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZpGdiBeTBKjkL2zdl9mb_RyfEfw7xNs',
    appId: '1:35179312839:web:6873ebac537be434d970e2',
    messagingSenderId: '35179312839',
    projectId: 'my-fitness-tracker-ddd68',
    authDomain: 'my-fitness-tracker-ddd68.firebaseapp.com',
    storageBucket: 'my-fitness-tracker-ddd68.appspot.com',
    measurementId: 'G-ZL3MJQ4J7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBal76XhwdHVp9N44BfcM-_3X7ZUnJi5HE',
    appId: '1:35179312839:android:3d11943b25c1eda0d970e2',
    messagingSenderId: '35179312839',
    projectId: 'my-fitness-tracker-ddd68',
    storageBucket: 'my-fitness-tracker-ddd68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9h1ff1qlI2QIHj-xPBnw2TTF59_-umAo',
    appId: '1:35179312839:ios:190bc5a4056b49cfd970e2',
    messagingSenderId: '35179312839',
    projectId: 'my-fitness-tracker-ddd68',
    storageBucket: 'my-fitness-tracker-ddd68.appspot.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9h1ff1qlI2QIHj-xPBnw2TTF59_-umAo',
    appId: '1:35179312839:ios:190bc5a4056b49cfd970e2',
    messagingSenderId: '35179312839',
    projectId: 'my-fitness-tracker-ddd68',
    storageBucket: 'my-fitness-tracker-ddd68.appspot.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );
}
